PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/doctest.py", line 1501, in run
    sys.settrace(save_trace)


===========================================================
If you don't see any results, all tests passed.
===========================================================
Run with the -v flag to show results regardless.
Hit up arrow (to get last command) and add space -v
===========================================================

Read error messages carefully.
Errors tell which line number has the error
and what the issue is. Scroll up in the terminal to see.
Fix issues one at a time until you get the behavior
Described in the docstring.
(base) Shantis-MacBook-Pro:datafun-02-functions shantikandel$ 